### ISSUE TITLE
PROTOCOL: MH - Managing your hoop combo

### ISSUE THREAD

**Issue by OompyBoi** [FeroxFoxxo/MQReawakened#33]
![image](https://user-images.githubusercontent.com/124912216/218086757-8f4ff77a-f05e-4696-8919-6cd542682036.png)

While trying to complete the ring combo in the area of CTS shown below, this packet issue pops up **when you hit the ground or a bounce pad two times during the combo attempt.** Also appears when you actually **finish the ring combo.**

![image](https://user-images.githubusercontent.com/124912216/218087451-cea3bc9a-0efa-4784-9302-dad94c9ffd5e.png)

**Comment by emsbro100** [comment]
Requires implementation of the medal/achievement system which hasn't been completed yet. This protocol itself isn't difficult but the prerequisite functions are so I have updated the labels accordingly.
