### ISSUE TITLE
bin folder missing

### ISSUE THREAD

**Issue by umicho7** [FeroxFoxxo/MQReawakened#91]
bin folder in Init folder needs to have Init.exe

**Comment by FeroxFoxxo** [comment]
It should do! Are you sure it's building correctly?

**Comment by umicho7** [comment]
![Screenshot 2024-01-08 172851](https://github.com/FeroxFoxxo/MQReawakened/assets/133949148/cf632db9-80c8-4c12-b549-fcefcf51047b)
[
![Screenshot 2024-01-08 173002](https://github.com/FeroxFoxxo/MQReawakened/assets/133949148/ef20b862-37fd-4818-8df1-0d2833d00c91)
](url)

**Comment by FeroxFoxxo** [comment]
Hi! Could you please go into the GitChanges menu at the bottom right and press the sync/update button? It might have been fixed in a recent push.

**Comment by umicho7** [comment]
Yes, thank you!! It worked :)
